### PR TITLE
Use IAM API credentials when assuming a role. Fixes #330

### LINKED ISSUE #330: Get S3 Access Denied, Maybe because of configuration
I'm pretty sure the AK/SK, role_arn and bucket name are correct. I don't know if there is somethin wrong on the configuration.
the configuration look like this:
```
<match kubernetes.**>
      @type copy

      # for debug
      # <store>
      #  @type file
      #  path /fluentd/docker.log
      #  format json
      #  include_time_key true
      #  time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      # </store>
      <store>
        @type s3
        @log_level debug

        auto_create_bucket false
        check_bucket false
        check_apikey_on_start false
        check_object false

        aws_key_id xxx
        aws_sec_key xxx
        s3_bucket bucket
        s3_region xxx
        path logs

        <assume_role_credentials>
          role_arn   xxx
          role_session_name xxx
        </assume_role_credentials>

        format json

        # if you want to use ${tag} or %Y/%m/%d/ like syntax in path / s3_object_key_format,
        # need to specify tag for ${tag} and time for %Y/%m/%d in <buffer> argument.
        <buffer kube_uid,time>
          @type file
          path /fluent/s3_buffer
          timekey 60 # 1 min partition
          timekey_wait 1m
          timekey_use_utc true # use utc
          chunk_limit_size 256m
        </buffer>
      </store>

</match>

```

Get the fluentd logs look like this:
```
failed to flush the buffer. retry_time=0 next_retry_seconds=2020-05-25 07:57:05 +0000 chunk="5a6744c1ce918d02269eaf6329cb4f63" error_class=Aws::S3::Errors::AccessDenied error="Access Denied"
```

The role policy looks like this:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:Put*",
                "s3:ListBucket",
                "s3:Get*",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucket/*",
                "arn:aws:s3:::bucket"
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by jotes**
Hi,
Disclaimer:  I'm not a ruby developer.

The PR fixes the issue mentioned in #330. I had added a couple of unit tests to check the existing functionality and noticed a few strange things e.g. I couldn't find the place in which @region gets initialized, some of conditions are probably redundant (?).
I would appreaciate a thorough review :)
Thanks in advance!

### CODE REVIEW

File: lib/fluent/plugin/out_s3.rb [hunk 1]
```diff
@@ -486,21 +485,19 @@ def setup_credentials
         credentials_options[:sts_endpoint_url] = c.sts_endpoint_url if c.sts_endpoint_url
         credentials_options[:sts_http_proxy] = c.sts_http_proxy if c.sts_http_proxy
         if c.sts_http_proxy && c.sts_endpoint_url
-          credentials_options[:client] = Aws::STS::Client.new(http_proxy: c.sts_http_proxy, endpoint: c.sts_endpoint_url)
-        elsif @region && c.sts_http_proxy
-          credentials_options[:client] = Aws::STS::Client.new(region: @region, http_proxy: c.sts_http_proxy)
-        elsif @region && c.sts_endpoint_url
```
Comment (jotes) [inline lib/fluent/plugin/out_s3.rb:492]: I couldn't find a place where `@region` is initliazed

**Comment by repeatedly** [comment]
Sorry. I forgot to merge this patch.
I will release new version soon.

**Comment by agup006** [comment]
Hey @jotes, congrats on your first merged PR 🎉 Nice work 👍 Please let me know if we can be helpful in any way.
